/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface":                   "#10141a",
        "surface-dim":               "#10141a",
        "surface-bright":            "#353940",
        "surface-container-lowest":  "#0a0e14",
        "surface-container-low":     "#181c22",
        "surface-container":         "#1c2026",
        "surface-container-high":    "#262a31",
        "surface-container-highest": "#31353c",
        "surface-variant":           "#31353c",
        "background":                "#10141a",
        "on-surface":                "#dfe2eb",
        "on-surface-variant":        "#c2c6d6",
        "on-background":             "#dfe2eb",
        "primary":                   "#adc6ff",
        "primary-container":         "#4b8eff",
        "on-primary":                "#002e69",
        "on-primary-fixed":          "#001a41",
        "inverse-primary":           "#005bc1",
        "secondary":                 "#c2c7d0",
        "secondary-container":       "#42474f",
        "on-secondary":              "#2c3138",
        "on-secondary-container":    "#b1b5bf",
        "tertiary":                  "#c1c7d0",
        "on-tertiary":               "#2b3138",
        "error":                     "#ffb4ab",
        "error-container":           "#93000a",
        "on-error":                  "#690005",
        "outline":                   "#8c909f",
        "outline-variant":           "#424754",
        "inverse-surface":           "#dfe2eb",
        "inverse-on-surface":        "#2d3137",
        "surface-tint":              "#adc6ff",
      },
      spacing: {
        "sidebar_width_expanded":  "240px",
        "margin-main":             "1.5rem",
        "stack-gap":               "0.75rem",
        "panel-padding":           "1.25rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Consolas", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      keyframes: {
        "fade-in":    { "0%": { opacity: "0", transform: "translateY(4px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "slide-in":   { "0%": { opacity: "0", transform: "translateX(-8px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        "pulse-slow": { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0.4" } },
      },
      animation: {
        "fade-in":  "fade-in 0.15s ease-out",
        "slide-in": "slide-in 0.2s ease-out",
      },
    },
  },
  plugins: [],
};
