"""
packages.py — ENVIX Package Hub Database

This file is the single source of truth for everything Package Hub shows.
Adding a new package is as simple as adding a new dict to the PACKAGES list.

Each package dict has these fields:
    id          : unique short ID used internally (no spaces)
    name        : display name shown in the UI
    language    : "python" | "node" | "java" | "go"
                  Must match a key in tools.py so we can check if it's installed.
    category    : e.g. "Web Framework", "Data Science", "Testing", etc.
                  Used to organize cards visually (shown on the card as a tag).
    description : one short sentence explaining what it does.
    install_cmd : the EXACT command to install this package locally.
                  Use {folder} as a placeholder — package_hub.py replaces it
                  with the actual target folder path at install time.
                  Examples:
                    "pip install numpy"
                    "npm install react"
                    "go get github.com/gin-gonic/gin"
    global_cmd  : command to install GLOBALLY (used when user picks "Install Globally").
                  Often the same as install_cmd but without a venv prefix.
    recommends  : list of package IDs from this same file that go well together.
                  These appear as clickable one-click install buttons on the card.
"""

PACKAGES = [

    # ── PYTHON ───────────────────────────────────────────────────────────────────

    {
        "id":          "numpy",
        "name":        "NumPy",
        "language":    "python",
        "category":    "Data Science",
        "description": "Fast numerical arrays and math for Python.",
        "install_cmd": "pip install numpy",
        "global_cmd":  "pip install numpy",
        "recommends":  ["pandas", "matplotlib", "scipy"],
    },
    {
        "id":          "pandas",
        "name":        "Pandas",
        "language":    "python",
        "category":    "Data Science",
        "description": "DataFrames for loading, cleaning, and analysing data.",
        "install_cmd": "pip install pandas",
        "global_cmd":  "pip install pandas",
        "recommends":  ["numpy", "matplotlib", "seaborn"],
    },
    {
        "id":          "matplotlib",
        "name":        "Matplotlib",
        "language":    "python",
        "category":    "Data Science",
        "description": "The classic Python plotting and graphing library.",
        "install_cmd": "pip install matplotlib",
        "global_cmd":  "pip install matplotlib",
        "recommends":  ["seaborn", "pandas", "numpy"],
    },
    {
        "id":          "seaborn",
        "name":        "Seaborn",
        "language":    "python",
        "category":    "Data Science",
        "description": "Beautiful statistical plots built on top of Matplotlib.",
        "install_cmd": "pip install seaborn",
        "global_cmd":  "pip install seaborn",
        "recommends":  ["matplotlib", "pandas"],
    },
    {
        "id":          "scipy",
        "name":        "SciPy",
        "language":    "python",
        "category":    "Data Science",
        "description": "Scientific algorithms: optimization, integration, signal processing.",
        "install_cmd": "pip install scipy",
        "global_cmd":  "pip install scipy",
        "recommends":  ["numpy", "pandas"],
    },
    {
        "id":          "scikit-learn",
        "name":        "Scikit-learn",
        "language":    "python",
        "category":    "Machine Learning",
        "description": "Simple and efficient tools for machine learning in Python.",
        "install_cmd": "pip install scikit-learn",
        "global_cmd":  "pip install scikit-learn",
        "recommends":  ["numpy", "pandas", "matplotlib"],
    },
    {
        "id":          "tensorflow",
        "name":        "TensorFlow",
        "language":    "python",
        "category":    "Machine Learning",
        "description": "Google's open-source deep learning framework.",
        "install_cmd": "pip install tensorflow",
        "global_cmd":  "pip install tensorflow",
        "recommends":  ["numpy", "pandas", "scikit-learn"],
    },
    {
        "id":          "torch",
        "name":        "PyTorch",
        "language":    "python",
        "category":    "Machine Learning",
        "description": "Meta's deep learning framework, popular for research.",
        "install_cmd": "pip install torch",
        "global_cmd":  "pip install torch",
        "recommends":  ["numpy", "transformers"],
    },
    {
        "id":          "fastapi",
        "name":        "FastAPI",
        "language":    "python",
        "category":    "Web Framework",
        "description": "Modern, fast API framework with automatic docs.",
        "install_cmd": "pip install fastapi",
        "global_cmd":  "pip install fastapi",
        "recommends":  ["uvicorn", "pydantic", "python-dotenv", "requests"],
    },
    {
        "id":          "flask",
        "name":        "Flask",
        "language":    "python",
        "category":    "Web Framework",
        "description": "Lightweight web framework — great for small APIs.",
        "install_cmd": "pip install flask",
        "global_cmd":  "pip install flask",
        "recommends":  ["requests", "python-dotenv", "sqlalchemy"],
    },
    {
        "id":          "django",
        "name":        "Django",
        "language":    "python",
        "category":    "Web Framework",
        "description": "Full-featured web framework with ORM, admin, and auth built in.",
        "install_cmd": "pip install django",
        "global_cmd":  "pip install django",
        "recommends":  ["sqlalchemy", "python-dotenv", "requests"],
    },
    {
        "id":          "requests",
        "name":        "Requests",
        "language":    "python",
        "category":    "Networking",
        "description": "The friendliest way to make HTTP requests in Python.",
        "install_cmd": "pip install requests",
        "global_cmd":  "pip install requests",
        "recommends":  ["python-dotenv"],
    },
    {
        "id":          "beautifulsoup4",
        "name":        "BeautifulSoup4",
        "language":    "python",
        "category":    "Web Scraping",
        "description": "Parse and extract data from HTML and XML files.",
        "install_cmd": "pip install beautifulsoup4",
        "global_cmd":  "pip install beautifulsoup4",
        "recommends":  ["requests"],
    },
    {
        "id":          "sqlalchemy",
        "name":        "SQLAlchemy",
        "language":    "python",
        "category":    "Database",
        "description": "Python SQL toolkit and ORM for database access.",
        "install_cmd": "pip install sqlalchemy",
        "global_cmd":  "pip install sqlalchemy",
        "recommends":  ["python-dotenv"],
    },
    {
        "id":          "opencv-python",
        "name":        "OpenCV",
        "language":    "python",
        "category":    "Computer Vision",
        "description": "Real-time computer vision — image and video processing.",
        "install_cmd": "pip install opencv-python",
        "global_cmd":  "pip install opencv-python",
        "recommends":  ["numpy", "pillow"],
    },
    {
        "id":          "pillow",
        "name":        "Pillow",
        "language":    "python",
        "category":    "Image Processing",
        "description": "Image manipulation: resize, crop, convert, filter.",
        "install_cmd": "pip install pillow",
        "global_cmd":  "pip install pillow",
        "recommends":  ["numpy"],
    },
    {
        "id":          "jupyterlab",
        "name":        "JupyterLab",
        "language":    "python",
        "category":    "Development Tools",
        "description": "The modern notebook interface for interactive Python.",
        "install_cmd": "pip install jupyterlab",
        "global_cmd":  "pip install jupyterlab",
        "recommends":  ["pandas", "matplotlib", "numpy"],
    },
    {
        "id":          "notebook",
        "name":        "Jupyter Notebook",
        "language":    "python",
        "category":    "Development Tools",
        "description": "Classic Jupyter notebook environment.",
        "install_cmd": "pip install notebook",
        "global_cmd":  "pip install notebook",
        "recommends":  ["pandas", "matplotlib"],
    },
    {
        "id":          "pydantic",
        "name":        "Pydantic",
        "language":    "python",
        "category":    "Data Validation",
        "description": "Data validation using Python type hints.",
        "install_cmd": "pip install pydantic",
        "global_cmd":  "pip install pydantic",
        "recommends":  ["fastapi"],
    },
    {
        "id":          "python-dotenv",
        "name":        "Python-dotenv",
        "language":    "python",
        "category":    "Configuration",
        "description": "Load environment variables from a .env file.",
        "install_cmd": "pip install python-dotenv",
        "global_cmd":  "pip install python-dotenv",
        "recommends":  [],
    },
    {
        "id":          "uvicorn",
        "name":        "Uvicorn",
        "language":    "python",
        "category":    "Web Framework",
        "description": "Lightning-fast ASGI server — runs FastAPI in production.",
        "install_cmd": "pip install uvicorn",
        "global_cmd":  "pip install uvicorn",
        "recommends":  ["fastapi"],
    },
    {
        "id":          "celery",
        "name":        "Celery",
        "language":    "python",
        "category":    "Task Queue",
        "description": "Distributed task queue for background jobs.",
        "install_cmd": "pip install celery",
        "global_cmd":  "pip install celery",
        "recommends":  ["redis"],
    },
    {
        "id":          "redis",
        "name":        "Redis (Python client)",
        "language":    "python",
        "category":    "Database",
        "description": "Python client for the Redis in-memory data store.",
        "install_cmd": "pip install redis",
        "global_cmd":  "pip install redis",
        "recommends":  ["celery"],
    },
    {
        "id":          "pytest",
        "name":        "Pytest",
        "language":    "python",
        "category":    "Testing",
        "description": "The most popular Python testing framework.",
        "install_cmd": "pip install pytest",
        "global_cmd":  "pip install pytest",
        "recommends":  [],
    },
    {
        "id":          "streamlit",
        "name":        "Streamlit",
        "language":    "python",
        "category":    "Data Apps",
        "description": "Build interactive data dashboards with pure Python.",
        "install_cmd": "pip install streamlit",
        "global_cmd":  "pip install streamlit",
        "recommends":  ["pandas", "matplotlib"],
    },
    {
        "id":          "gradio",
        "name":        "Gradio",
        "language":    "python",
        "category":    "Data Apps",
        "description": "Build shareable ML demos with a few lines of code.",
        "install_cmd": "pip install gradio",
        "global_cmd":  "pip install gradio",
        "recommends":  ["torch", "transformers"],
    },
    {
        "id":          "langchain",
        "name":        "LangChain",
        "language":    "python",
        "category":    "AI / LLM",
        "description": "Framework for building LLM-powered applications.",
        "install_cmd": "pip install langchain",
        "global_cmd":  "pip install langchain",
        "recommends":  ["python-dotenv", "requests"],
    },
    {
        "id":          "transformers",
        "name":        "Transformers",
        "language":    "python",
        "category":    "AI / LLM",
        "description": "Hugging Face library for pre-trained transformer models.",
        "install_cmd": "pip install transformers",
        "global_cmd":  "pip install transformers",
        "recommends":  ["torch", "numpy"],
    },
    {
        "id":          "llama-index",
        "name":        "LlamaIndex",
        "language":    "python",
        "category":    "AI / LLM",
        "description": "Connect LLMs to your own data sources.",
        "install_cmd": "pip install llama-index",
        "global_cmd":  "pip install llama-index",
        "recommends":  ["langchain", "python-dotenv"],
    },
    {
        "id":          "poetry",
        "name":        "Poetry",
        "language":    "python",
        "category":    "Development Tools",
        "description": "Modern Python dependency management and packaging.",
        "install_cmd": "pip install poetry",
        "global_cmd":  "pip install poetry",
        "recommends":  [],
    },
    {
        "id":          "black",
        "name":        "Black",
        "language":    "python",
        "category":    "Code Quality",
        "description": "The uncompromising Python code formatter.",
        "install_cmd": "pip install black",
        "global_cmd":  "pip install black",
        "recommends":  ["isort", "ruff"],
    },
    {
        "id":          "isort",
        "name":        "isort",
        "language":    "python",
        "category":    "Code Quality",
        "description": "Automatically sorts Python import statements.",
        "install_cmd": "pip install isort",
        "global_cmd":  "pip install isort",
        "recommends":  ["black"],
    },
    {
        "id":          "ruff",
        "name":        "Ruff",
        "language":    "python",
        "category":    "Code Quality",
        "description": "Extremely fast Python linter — replaces flake8, pylint.",
        "install_cmd": "pip install ruff",
        "global_cmd":  "pip install ruff",
        "recommends":  ["black"],
    },

    # ── NODE.JS ──────────────────────────────────────────────────────────────────

    {
        "id":          "react",
        "name":        "React",
        "language":    "node",
        "category":    "UI Framework",
        "description": "The most popular library for building user interfaces.",
        "install_cmd": "npm install react react-dom",
        "global_cmd":  "npm install -g create-react-app",
        "recommends":  ["react-router-dom", "axios", "redux-toolkit", "tailwindcss"],
    },
    {
        "id":          "next",
        "name":        "Next.js",
        "language":    "node",
        "category":    "UI Framework",
        "description": "React framework with file-based routing and SSR.",
        "install_cmd": "npm install next react react-dom",
        "global_cmd":  "npm install -g create-next-app",
        "recommends":  ["tailwindcss", "axios", "prisma"],
    },
    {
        "id":          "express",
        "name":        "Express",
        "language":    "node",
        "category":    "Backend Framework",
        "description": "Minimal and flexible Node.js web framework.",
        "install_cmd": "npm install express",
        "global_cmd":  "npm install express",
        "recommends":  ["nodemon", "typescript"],
    },
    {
        "id":          "nestjs",
        "name":        "NestJS",
        "language":    "node",
        "category":    "Backend Framework",
        "description": "Progressive Node.js framework for scalable server-side apps.",
        "install_cmd": "npm install @nestjs/core @nestjs/common",
        "global_cmd":  "npm install -g @nestjs/cli",
        "recommends":  ["typescript"],
    },
    {
        "id":          "vue",
        "name":        "Vue",
        "language":    "node",
        "category":    "UI Framework",
        "description": "Progressive JavaScript framework for building UIs.",
        "install_cmd": "npm install vue",
        "global_cmd":  "npm install -g @vue/cli",
        "recommends":  ["vite", "axios", "typescript"],
    },
    {
        "id":          "angular",
        "name":        "Angular",
        "language":    "node",
        "category":    "UI Framework",
        "description": "Google's platform for building large-scale web apps.",
        "install_cmd": "npm install @angular/core @angular/common",
        "global_cmd":  "npm install -g @angular/cli",
        "recommends":  ["typescript"],
    },
    {
        "id":          "svelte",
        "name":        "Svelte",
        "language":    "node",
        "category":    "UI Framework",
        "description": "Compiler-based UI framework — no virtual DOM.",
        "install_cmd": "npm install svelte",
        "global_cmd":  "npm install svelte",
        "recommends":  ["vite"],
    },
    {
        "id":          "tailwindcss",
        "name":        "TailwindCSS",
        "language":    "node",
        "category":    "Styling",
        "description": "Utility-first CSS framework for rapid UI development.",
        "install_cmd": "npm install -D tailwindcss postcss autoprefixer",
        "global_cmd":  "npm install -D tailwindcss",
        "recommends":  [],
    },
    {
        "id":          "axios",
        "name":        "Axios",
        "language":    "node",
        "category":    "Networking",
        "description": "Promise-based HTTP client for browser and Node.js.",
        "install_cmd": "npm install axios",
        "global_cmd":  "npm install axios",
        "recommends":  [],
    },
    {
        "id":          "socket.io",
        "name":        "Socket.io",
        "language":    "node",
        "category":    "Networking",
        "description": "Real-time bidirectional event-based communication.",
        "install_cmd": "npm install socket.io",
        "global_cmd":  "npm install socket.io",
        "recommends":  ["express"],
    },
    {
        "id":          "prisma",
        "name":        "Prisma",
        "language":    "node",
        "category":    "Database",
        "description": "Modern TypeScript ORM with auto-generated types.",
        "install_cmd": "npm install prisma @prisma/client",
        "global_cmd":  "npm install -g prisma",
        "recommends":  ["typescript"],
    },
    {
        "id":          "typescript",
        "name":        "TypeScript",
        "language":    "node",
        "category":    "Language",
        "description": "Typed JavaScript — catch errors before they run.",
        "install_cmd": "npm install -D typescript ts-node @types/node",
        "global_cmd":  "npm install -g typescript",
        "recommends":  [],
    },
    {
        "id":          "redux-toolkit",
        "name":        "Redux Toolkit",
        "language":    "node",
        "category":    "State Management",
        "description": "The official, opinionated Redux toolkit for simpler state.",
        "install_cmd": "npm install @reduxjs/toolkit react-redux",
        "global_cmd":  "npm install @reduxjs/toolkit",
        "recommends":  ["react"],
    },
    {
        "id":          "react-router-dom",
        "name":        "React Router",
        "language":    "node",
        "category":    "Routing",
        "description": "Declarative routing for React applications.",
        "install_cmd": "npm install react-router-dom",
        "global_cmd":  "npm install react-router-dom",
        "recommends":  ["react"],
    },
    {
        "id":          "vite",
        "name":        "Vite",
        "language":    "node",
        "category":    "Build Tools",
        "description": "Next-generation frontend build tool — blazing fast.",
        "install_cmd": "npm install -D vite",
        "global_cmd":  "npm install -g vite",
        "recommends":  [],
    },
    {
        "id":          "webpack",
        "name":        "Webpack",
        "language":    "node",
        "category":    "Build Tools",
        "description": "Module bundler that processes JS, CSS, and assets.",
        "install_cmd": "npm install -D webpack webpack-cli",
        "global_cmd":  "npm install -D webpack",
        "recommends":  ["babel"],
    },
    {
        "id":          "babel",
        "name":        "Babel",
        "language":    "node",
        "category":    "Build Tools",
        "description": "JavaScript transpiler — use modern JS in older browsers.",
        "install_cmd": "npm install -D @babel/core @babel/preset-env",
        "global_cmd":  "npm install -D @babel/core",
        "recommends":  ["webpack"],
    },
    {
        "id":          "eslint",
        "name":        "ESLint",
        "language":    "node",
        "category":    "Code Quality",
        "description": "Pluggable JavaScript linter to catch errors early.",
        "install_cmd": "npm install -D eslint",
        "global_cmd":  "npm install -g eslint",
        "recommends":  ["prettier"],
    },
    {
        "id":          "prettier",
        "name":        "Prettier",
        "language":    "node",
        "category":    "Code Quality",
        "description": "Opinionated code formatter — works across many languages.",
        "install_cmd": "npm install -D prettier",
        "global_cmd":  "npm install -g prettier",
        "recommends":  ["eslint"],
    },
    {
        "id":          "jest",
        "name":        "Jest",
        "language":    "node",
        "category":    "Testing",
        "description": "Delightful JavaScript testing framework by Meta.",
        "install_cmd": "npm install -D jest",
        "global_cmd":  "npm install -g jest",
        "recommends":  [],
    },
    {
        "id":          "vitest",
        "name":        "Vitest",
        "language":    "node",
        "category":    "Testing",
        "description": "Vite-native unit testing framework — fast and modern.",
        "install_cmd": "npm install -D vitest",
        "global_cmd":  "npm install -D vitest",
        "recommends":  ["vite"],
    },
    {
        "id":          "mocha",
        "name":        "Mocha",
        "language":    "node",
        "category":    "Testing",
        "description": "Feature-rich JS test framework for Node and browser.",
        "install_cmd": "npm install -D mocha",
        "global_cmd":  "npm install -g mocha",
        "recommends":  [],
    },
    {
        "id":          "nodemon",
        "name":        "Nodemon",
        "language":    "node",
        "category":    "Development Tools",
        "description": "Automatically restarts Node.js when files change.",
        "install_cmd": "npm install -D nodemon",
        "global_cmd":  "npm install -g nodemon",
        "recommends":  ["express"],
    },
    {
        "id":          "fastify",
        "name":        "Fastify",
        "language":    "node",
        "category":    "Backend Framework",
        "description": "High-performance web framework — faster than Express.",
        "install_cmd": "npm install fastify",
        "global_cmd":  "npm install fastify",
        "recommends":  ["typescript"],
    },
    {
        "id":          "electron",
        "name":        "Electron",
        "language":    "node",
        "category":    "Desktop Apps",
        "description": "Build cross-platform desktop apps with web technologies.",
        "install_cmd": "npm install -D electron",
        "global_cmd":  "npm install -g electron",
        "recommends":  [],
    },
    {
        "id":          "playwright",
        "name":        "Playwright",
        "language":    "node",
        "category":    "Testing",
        "description": "Cross-browser end-to-end testing by Microsoft.",
        "install_cmd": "npm install -D playwright",
        "global_cmd":  "npm install -g playwright",
        "recommends":  [],
    },
    {
        "id":          "cypress",
        "name":        "Cypress",
        "language":    "node",
        "category":    "Testing",
        "description": "End-to-end testing for web apps — great developer experience.",
        "install_cmd": "npm install -D cypress",
        "global_cmd":  "npm install -g cypress",
        "recommends":  [],
    },

    # ── JAVA ─────────────────────────────────────────────────────────────────────
    # Java packages are installed via Maven or Gradle, not a package manager CLI.
    # The install_cmd here adds the dependency to pom.xml (Maven) or build.gradle.
    # We use a shell command that echoes the dependency block — the user can also
    # copy it manually. For full Maven/Gradle automation, a build file would need
    # to be parsed, which is beyond ENVIX's current scope.

    {
        "id":          "spring-boot",
        "name":        "Spring Boot",
        "language":    "java",
        "category":    "Web Framework",
        "description": "Build production-ready Spring applications quickly.",
        "install_cmd": "echo 'Add to pom.xml: spring-boot-starter-web'",
        "global_cmd":  "echo 'Add to pom.xml: spring-boot-starter-web'",
        "recommends":  ["spring-data", "spring-security"],
    },
    {
        "id":          "spring-security",
        "name":        "Spring Security",
        "language":    "java",
        "category":    "Security",
        "description": "Authentication and access-control for Spring apps.",
        "install_cmd": "echo 'Add to pom.xml: spring-boot-starter-security'",
        "global_cmd":  "echo 'Add to pom.xml: spring-boot-starter-security'",
        "recommends":  ["spring-boot"],
    },
    {
        "id":          "spring-data",
        "name":        "Spring Data",
        "language":    "java",
        "category":    "Database",
        "description": "Database access with repository pattern for Spring.",
        "install_cmd": "echo 'Add to pom.xml: spring-boot-starter-data-jpa'",
        "global_cmd":  "echo 'Add to pom.xml: spring-boot-starter-data-jpa'",
        "recommends":  ["hibernate", "spring-boot"],
    },
    {
        "id":          "maven",
        "name":        "Maven",
        "language":    "java",
        "category":    "Build Tools",
        "description": "Standard Java build tool and dependency manager.",
        "install_cmd": "echo 'Install via: winget install Apache.Maven'",
        "global_cmd":  "winget install Apache.Maven",
        "recommends":  [],
    },
    {
        "id":          "gradle",
        "name":        "Gradle",
        "language":    "java",
        "category":    "Build Tools",
        "description": "Flexible build automation — used by Android and Spring.",
        "install_cmd": "echo 'Install via: winget install Gradle.Gradle'",
        "global_cmd":  "winget install Gradle.Gradle",
        "recommends":  [],
    },
    {
        "id":          "junit",
        "name":        "JUnit",
        "language":    "java",
        "category":    "Testing",
        "description": "The standard Java unit testing framework.",
        "install_cmd": "echo 'Add to pom.xml: junit-vintage-engine'",
        "global_cmd":  "echo 'Add to pom.xml: junit-vintage-engine'",
        "recommends":  ["mockito"],
    },
    {
        "id":          "hibernate",
        "name":        "Hibernate",
        "language":    "java",
        "category":    "Database",
        "description": "Object-relational mapping (ORM) for Java.",
        "install_cmd": "echo 'Add to pom.xml: hibernate-core'",
        "global_cmd":  "echo 'Add to pom.xml: hibernate-core'",
        "recommends":  ["spring-data"],
    },
    {
        "id":          "lombok",
        "name":        "Lombok",
        "language":    "java",
        "category":    "Development Tools",
        "description": "Reduce Java boilerplate with annotations (@Data, @Builder).",
        "install_cmd": "echo 'Add to pom.xml: lombok'",
        "global_cmd":  "echo 'Add to pom.xml: lombok'",
        "recommends":  [],
    },
    {
        "id":          "log4j",
        "name":        "Log4j",
        "language":    "java",
        "category":    "Logging",
        "description": "Popular Java logging framework.",
        "install_cmd": "echo 'Add to pom.xml: log4j-core'",
        "global_cmd":  "echo 'Add to pom.xml: log4j-core'",
        "recommends":  [],
    },
    {
        "id":          "jackson",
        "name":        "Jackson",
        "language":    "java",
        "category":    "Data",
        "description": "Fast JSON serialisation/deserialisation for Java.",
        "install_cmd": "echo 'Add to pom.xml: jackson-databind'",
        "global_cmd":  "echo 'Add to pom.xml: jackson-databind'",
        "recommends":  [],
    },
    {
        "id":          "apache-commons",
        "name":        "Apache Commons",
        "language":    "java",
        "category":    "Utilities",
        "description": "Reusable Java utilities — strings, IO, collections.",
        "install_cmd": "echo 'Add to pom.xml: commons-lang3'",
        "global_cmd":  "echo 'Add to pom.xml: commons-lang3'",
        "recommends":  [],
    },
    {
        "id":          "junit-jupiter",
        "name":        "JUnit Jupiter",
        "language":    "java",
        "category":    "Testing",
        "description": "JUnit 5 — the next generation of Java testing.",
        "install_cmd": "echo 'Add to pom.xml: junit-jupiter'",
        "global_cmd":  "echo 'Add to pom.xml: junit-jupiter'",
        "recommends":  ["mockito"],
    },
    {
        "id":          "mockito",
        "name":        "Mockito",
        "language":    "java",
        "category":    "Testing",
        "description": "Mocking framework for Java unit tests.",
        "install_cmd": "echo 'Add to pom.xml: mockito-core'",
        "global_cmd":  "echo 'Add to pom.xml: mockito-core'",
        "recommends":  ["junit-jupiter"],
    },

    # ── GO ───────────────────────────────────────────────────────────────────────

    {
        "id":          "gin",
        "name":        "Gin",
        "language":    "go",
        "category":    "Web Framework",
        "description": "Fast HTTP web framework for Go with a martini-like API.",
        "install_cmd": "go get github.com/gin-gonic/gin",
        "global_cmd":  "go install github.com/gin-gonic/gin@latest",
        "recommends":  ["zap", "viper"],
    },
    {
        "id":          "fiber",
        "name":        "Fiber",
        "language":    "go",
        "category":    "Web Framework",
        "description": "Express-inspired Go web framework built on Fasthttp.",
        "install_cmd": "go get github.com/gofiber/fiber/v2",
        "global_cmd":  "go get github.com/gofiber/fiber/v2",
        "recommends":  ["zap"],
    },
    {
        "id":          "echo",
        "name":        "Echo",
        "language":    "go",
        "category":    "Web Framework",
        "description": "High-performance, minimalist Go web framework.",
        "install_cmd": "go get github.com/labstack/echo/v4",
        "global_cmd":  "go get github.com/labstack/echo/v4",
        "recommends":  ["zap"],
    },
    {
        "id":          "gorm",
        "name":        "GORM",
        "language":    "go",
        "category":    "Database",
        "description": "The fantastic ORM library for Go.",
        "install_cmd": "go get gorm.io/gorm",
        "global_cmd":  "go get gorm.io/gorm",
        "recommends":  ["gin"],
    },
    {
        "id":          "cobra",
        "name":        "Cobra",
        "language":    "go",
        "category":    "CLI",
        "description": "Library for building powerful CLI applications in Go.",
        "install_cmd": "go get github.com/spf13/cobra",
        "global_cmd":  "go install github.com/spf13/cobra-cli@latest",
        "recommends":  ["viper"],
    },
    {
        "id":          "viper",
        "name":        "Viper",
        "language":    "go",
        "category":    "Configuration",
        "description": "Complete configuration solution for Go applications.",
        "install_cmd": "go get github.com/spf13/viper",
        "global_cmd":  "go get github.com/spf13/viper",
        "recommends":  ["cobra"],
    },
    {
        "id":          "chi",
        "name":        "Chi",
        "language":    "go",
        "category":    "Web Framework",
        "description": "Lightweight and composable router for Go HTTP services.",
        "install_cmd": "go get github.com/go-chi/chi/v5",
        "global_cmd":  "go get github.com/go-chi/chi/v5",
        "recommends":  [],
    },
    {
        "id":          "zap",
        "name":        "Zap",
        "language":    "go",
        "category":    "Logging",
        "description": "Blazing-fast, structured logging for Go.",
        "install_cmd": "go get go.uber.org/zap",
        "global_cmd":  "go get go.uber.org/zap",
        "recommends":  [],
    },
    {
        "id":          "go-kit",
        "name":        "Go Kit",
        "language":    "go",
        "category":    "Microservices",
        "description": "Toolkit for building microservices in Go.",
        "install_cmd": "go get github.com/go-kit/kit",
        "global_cmd":  "go get github.com/go-kit/kit",
        "recommends":  ["zap"],
    },
    {
        "id":          "testify",
        "name":        "Testify",
        "language":    "go",
        "category":    "Testing",
        "description": "Toolkit with assertions and mocks for Go tests.",
        "install_cmd": "go get github.com/stretchr/testify",
        "global_cmd":  "go get github.com/stretchr/testify",
        "recommends":  [],
    },
]


# ── Quick lookup helpers ──────────────────────────────────────────────────────
# Build a dict keyed by package ID so we can find a package instantly
# without looping through the whole list. Used by the recommends feature.

PACKAGES_BY_ID = {pkg["id"]: pkg for pkg in PACKAGES}
